# > library(plumber)
# > library(recommenderlab)
# > library(reshape2)
# > library(tidyr)
# > library(Matrix)
# > library(plyr)
# > library(dplyr)

# > r = plumb("C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\travel_api.R") 
# > r$run(port = 8000)

#* @post /adduser
#* @param input:character generated by the user's input on the website
function(input) {
  travel_data_tidy = readRDS(file = "C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\travel_data_tidy.RData")
  # print(input)
  # travel_data_tidy <- read.csv(file.path(path, 'master_tidy.csv'), stringsAsFactors = FALSE)

  # save(travel_data_tidy, file=file.path(path,"travel_data_tidy.RData"))
  
  User <- data.frame(User = rep(sha1(Sys.time()),nrow(input)))
  user_input <- cbind(User, input) # unnecessary
  print(user_input)
  travel_data_tidy_new <- rbind(travel_data_tidy,user_input)

  # Start cleaning data to return
  
  vac_data = arrange(travel_data_tidy, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )
  
  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)
  
  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)
  
  ratings.real = new("realRatingMatrix", data = ratings)
  
  ratings.binary <- binarize(ratings.real, minRating = GOODRATING)
  
  travel_model = Recommender(ratings.binary, method = "UBCF", parameter = list(nn = 2))
  # -------------------------------------------------
  
  vac_data = arrange(travel_data_tidy_new, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )
  
  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)
  
  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)
  
  ratings.real = new("realRatingMatrix", data = ratings)
  
  ratings.binary.new <- binarize(ratings.real, minRating = GOODRATING)
  
  predictions = as(predict(travel_model, ratings.binary.new[nrow(ratings.binary.new)], n = 5), "list")
  print(predictions)
  saveRDS(travel_data_tidy_new, file=file.path(path, "travel_data_tidy.RData"))
}

# #* @get /rec
# #* @param input:character generated by the user's input on the website
# function(input){
#   
#   id <- data.frame(User = rep(sha1(Sys.time()), 5))
#   print(input)
#   user_input <- cbind(id, input)
#   print(user_input)
#  # user_matrix <- spread(user_input, Location, Rating)
# 
#   travel_data_tidy = readRDS(file = "C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\travel_data_tidy.RData")
# 
#   vac_data = arrange(travel_data_tidy, User) %>%
#     mutate(
#       User = factor(User, levels = unique(User)),
#       Location = factor(Location)
#     )
# 
#   ratings = sparseMatrix(i = as.integer(vac_data$User),
#                          j = as.integer(vac_data$Location),
#                          x = vac_data$Rating)
# 
#   rownames(ratings) = levels(vac_data$User)
#   colnames(ratings) = levels(vac_data$Location)
# 
#   ratings.real = new("realRatingMatrix", data = ratings)
# 
#   ratings.binary <- binarize(ratings.real, minRating = GOODRATING)
# 
#   travel_model = Recommender(ratings.binary, method = "UBCF", parameter = list(nn = 2))
# # -------------------------------------------------
#   travel_data_tidy_new = readRDS(file = "C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\travel_data_tidy.RData")
#   travel_data_tidy_new = rbind(travel_data_tidy_new, user_input)
# 
#   vac_data = arrange(travel_data_tidy_new, User) %>%
#     mutate(
#       User = factor(User, levels = unique(User)),
#       Location = factor(Location)
#     )
# 
#   ratings = sparseMatrix(i = as.integer(vac_data$User),
#                          j = as.integer(vac_data$Location),
#                          x = vac_data$Rating)
# 
#   rownames(ratings) = levels(vac_data$User)
#   colnames(ratings) = levels(vac_data$Location)
# 
#   ratings.real = new("realRatingMatrix", data = ratings)
# 
#   ratings.binary.new <- binarize(ratings.real, minRating = GOODRATING)
# 
#   predictions = as(predict(travel_model, ratings.binary.new[nrow(ratings.binary.new)], n = 5), "list")
#   print(predictions)
#   }
