# > library(plumber)
# > library(recommenderlab)
# > library(reshape2)
# > library(tidyr)
# > library(Matrix)
# > library(plyr)
# > library(dplyr)

# > r = plumb("C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\travel_api.R") 
# > r$run(port = 8000)

# input must match json object
#* @post /adduser
#* @param input:character generated by the user's input on the website
function(input) {
  travel_data_tidy = load(file = "travel_data_tidy.RData")
  
  # print(input)
  
  id <- rep(sha1(Sys.time()),5)
  user_input <- cbind(id, input)

  travel_data_tidy <- rbind(travel_data_tidy,user_input)
  save(travel_data_tidy, file="travel_data_tidy.RData")
}

#* @get /rec
#* @param input:character generated by the user's input on the website
function(input){
  
  id <- data.frame(User = rep(sha1(Sys.time()), 5))
  
  user_input <- cbind(id, input)
 # user_matrix <- spread(user_input, Location, Rating)

  travel_data_tidy = load(file = 'travel_data_tidy.RData')

  vac_data = arrange(travel_data_tidy, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )

  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)

  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)

  ratings.real = new("realRatingMatrix", data = ratings)

  ratings.binary <- binarize(ratings.real, minRating = GOODRATING)

  travel_model = Recommender(ratings.binary, method = "UBCF", parameter = list(nn = 2))
# -------------------------------------------------
  travel_data_tidy_new = load(file = 'travel_data_tidy.RData')
  travel_data_tidy_new = rbind(travel_data_tidy_new, user_input)

  vac_data = arrange(travel_data_tidy_new, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )

  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)

  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)

  ratings.real = new("realRatingMatrix", data = ratings)

  ratings.binary.new <- binarize(ratings.real, minRating = GOODRATING)


  predictions = as(predict(travel_model, ratings.binary.new[nrow(ratings.binary.new)], n = 5), "list")
  predictions
  }
