# > library(recommenderlab)
# > library(reshape2)
# > library(tidyr)
# > library(Matrix)
# > library(plyr)
# > library(dplyr)
# > r = plumb("C:\\Users\\Student\\Documents\\iX_Data_Science\\travel_api.R") 
# > r$run(port = 8000)

travel_data_tidy <- read.csv("C:\\Users\\Student\\Documents\\iX_Data_Science\\TravelRecs\\VacationRecs\\master_tidy.csv")

vac_data = arrange(travel_data_tidy, User) %>%
  mutate(
    User = factor(User, levels = unique(User)),
    Location = factor(Location)
  )

GOODRATING = 5

ratings = sparseMatrix(i = as.integer(vac_data$User),
                       j = as.integer(vac_data$Location),
                       x = vac_data$Rating)

rownames(ratings) = levels(vac_data$User)
colnames(ratings) = levels(vac_data$Location)

ratings.real = new("realRatingMatrix", data = ratings)

ratings.binary <- binarize(ratings.real, minRating = GOODRATING)

travel_model = Recommender(ratings.binary, method = "UBCF", parameter = list(nn = 2))

travel_matrix <- spread(travel_data_tidy,location,rating)
travel_matrix[is.na(travel_matrix)] <- 0
travel_matrix <- travel_matrix

#* @post /adduser
#* @param input:list generated by the user's input on the website
function(input) {
  travel_data_tidy = load(file = "travel_data_tidy.RData")
  
  input <- unlist(input)
  id <- rep(sha1(Sys.time()),5)
  user_input <- data.frame(User = id, Location = input[seq(1,10,2)], Rating = as.numeric(input[seq(2,10,2)]))
  
  travel_data_tidy <- rbind(travel_data_tidy,user_input)
  save(travel_data_tidy, file="travel_data_tidy.RData")
  
}

#* @get /rec
#* @param input:list generated by the user's input on the website
function(input){
  input <- unlist(input)
  id <- rep(sha1(Sys.time()), 5)
  
  user_input <- data.frame(User = id, Location = input[seq(1,10,2)], Rating = as.numeric(input[seq(2,10,2)]))
  user_matrix <- spread(user_input, Location, Rating)
  
  travel_data_tidy = load(file = 'travel_data_tidy.RData')
  
  travel_data_tidy_new = load(file = 'travel_data_tidy.RData')
  travel_data_tidy_new = rbind(travel_data_tidy_new, user_input)
  
  vac_data = arrange(travel_data_tidy, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )
  
  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)
  
  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)
  
  ratings.real = new("realRatingMatrix", data = ratings)
  
  ratings.binary <- binarize(ratings.real, minRating = GOODRATING)
# -------------------------------------------------
  vac_data = arrange(travel_data_tidy_new, User) %>%
    mutate(
      User = factor(User, levels = unique(User)),
      Location = factor(Location)
    )
  
  ratings = sparseMatrix(i = as.integer(vac_data$User),
                         j = as.integer(vac_data$Location),
                         x = vac_data$Rating)
  
  rownames(ratings) = levels(vac_data$User)
  colnames(ratings) = levels(vac_data$Location)
  
  ratings.real = new("realRatingMatrix", data = ratings)
  
  ratings.binary.new <- binarize(ratings.real, minRating = GOODRATING)
  
  travel_model = Recommender(ratings.binary, method = "UBCF", parameter = list(nn = 2))
  
  as(predict(travel_model, ratings.binary$User == user_input$User, n = 5), "list")
}
